# Generated by Django 2.0.7 on 2018-07-12 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('salary', models.PositiveSmallIntegerField()),
                ('tax_percent', models.PositiveSmallIntegerField()),
                ('extra_public_holiday_percent', models.PositiveSmallIntegerField()),
                ('extra_per_day', models.PositiveSmallIntegerField()),
                ('extra_additional_hour_percent', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userboard.Work')),
            ],
        ),
    ]
