# Generated by Django 2.0.7 on 2018-07-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userboard', '0002_auto_20180713_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
